### ISSUE TITLE
Memcached

### ISSUE THREAD

**Issue by flexgrip** [a1comms/GaeFlexSupportL5#42] opened 2019-08-23 23:20 UTC
Hello,

In my GAE Standard + Laravel app, I'm currently running a standalone redis instance (on GCE). It sucks. The VPC connector was unreliable, so I'm having to connect to it via the public IP. It sucks.

The original package that this repo was based on actually started implementing the native memcached from GAE. Does this repo plan on doing that?

I keep thinking if we just write a simple driver for memcached it might work. Curious what your thoughts are...

**Comment by iamacarpet** [comment] 2019-08-24 08:01
Hello @flexgrip 

I’m with you here, it does suck, as the native memcache available in php55 was pretty awesome.

It isn’t just a driver issue, support for it has been completely removed in the new php72 runtime and AFAIK same policy applies for all new versions for everything except the core languages, e.g. Java, Go.

Google were helpful with us when we reached out, but can’t discuss too much as it is covered under NDA.

However I do have contact details for the PM in charge of both App Engine & VPC Serverless Access, so I’ll send them a link to this issue and maybe they’ll be in touch.

For their benefit, do you have any details about how VPC Serverless Access was unreliable for you?

And have you tried Cloud Memorystore, instead of running redis yourself? I guess from their perspective it might be good if you can rule out it being VM related.

Regards,
iamacarpet

**Comment by flexgrip** [comment] 2019-08-30 23:31
Thanks @iamacarpet,

So my first attempt was with cloud memorystore. I managed to get it to work (again, I'm on GAE Standard). However, I noticed about two weeks before we went live that sometimes my appengine app would be dead because it would timeout trying to connect to cloud memorystore.

After confirming it wasn't my fault and then seeing the error return a few days later for another 4 hours, I decided that I couldn't trust it to go into production. So I stood up a GCE box that just runs redis. However, at that point and after hours and hours reading through docs, the VPC connector absolutely refused to connect to that GCE box. Made sure they were in the same zone, etc etc.

I pointed our production app at the public IP and boom. It worked. But I feel like that's just a crappy solution because now it has to go out over the internet and back into the datacenter to hit the cache. Which I think makes it useless.

The only function I'm getting out of it now is that at least I can clear the cache across all instances from the shared redis cache. But I'm looking for a better solution. I thought the native memcached would be it (python still supports it, and they sell dedicated memcached, so I'm not sure why the php runtime would drop support). Not saying you're wrong, just saying that that's a weird move.

I guess maybe I'll try getting that VPC connector to work again soon. But ultimately I'd like to revert back to cloud memorystore if I could trust it. It was so random. It would just die for a period of time and then finally just start working again. No code changes.

**Comment by iamacarpet** [comment] 2019-09-02 11:50
Thanks for the detailed write up @flexgrip ,

I passed a link to this issue over to the product managers at Google on the date of my first reply and haven't had anything back during the week I've been away from the office.

If nothing else, your comments are useful to us, as we're literally just about to start using the VPC Connector in production this week, but won't start using it for cache / Cloud Memorystore for a while yet, as there's only one of our projects that needs it and we're still a way off getting it migrated.

Just out of interest, what region are you using it in?

We are in "europe-west1" and the only connectivity problems we've noticed so far in our limited testing are when I was stupid enough to try and deploy with "gcloud app deploy" rather than "gcloud beta app deploy", as it deployed without any errors / warning, but totally ignored the VPC connector related stuff in the app.yaml file.

**Comment by flexgrip** [comment] 2019-09-03 00:11
We’re using us-central1.

In terms of the VPC connector giving me a private network from GAE to GCE, it has never worked at all for us. So I don’t know if it’s just misconfigured (totally possible) or a firewall issue, or maybe even it’s the bitnami redis template I used just isn’t connecting.

I just ssh’d into my redis box and ran `ifconfig` and I noticed that I only see one Ethernet device. You’d think I’d see two. One for the private subnet and one for the public one.

I’m in production now, so I guess I’ll try setting up a new redis box from scratch and making sure I start it off with two virtual nics.

I’d also really love to just use cloud memory store. But my gut tells me that the problems I was having had to do with the redis driver that Laravel uses + whatever connection settings that cloud memorystore wants. For instance, maybe the Laravel driver defaults to some weird setting like `keepalive=10` and cloud memory store handles that differently. That’s just an example and a made up configuration option. But I guess I’m just trying to say I think my issue was with fundamental driver issue, not an outage 

Thanks for listening to me complain so far :)

**Comment by iamacarpet** [comment] 2019-09-10 15:12
@flexgrip , it could be unrelated, but I may have been able to re-create your issue.

Going to spend some time properly investigating tomorrow and creating a re-producible sample to confirm, but in the meantime, could I ask if you used the PhpRedis extension to connect to Redis?

This is the one loaded via `extension=redis.so` in `php.ini`, which exposes the `Redis()` class.

I ask because I can't get this one to connect at all, "connection timeout" all the time, however connecting using the framework's default driver (which is basically `fsockopen` and text based i/o on the socket handle) works perfectly and still does if I switch back - I was just trying to switch it over the PhpRedis to see if it improved performance.

**Comment by flexgrip** [comment] 2019-09-10 19:09
I do have `redis.so` in my php.ini and `predis` is listed as the Laravel driver.

**Comment by flexgrip** [comment] 2019-09-10 19:12
I also tried supplying a timeout as well as a read_write_timeout parameter to my apps redis config. That didn’t seem to help.

However if you’re talking about this in relation to cloud memory store, it worked fine for a while. Then randomly timed out for a block of time.

If you mean over a vpc connector, it’s just never worked. Still haven’t tried standing up a new box. I might be able to give that a shot today.

**Comment by iamacarpet** [comment] 2019-09-12 19:25
Looks like it was just a mistake deploying without the “beta” in “gcloud beta app deploy” and getting confused about fsockopen still working, so afraid I can’t replicate yet.

We’re preparing to go into production next week with Cloud Memorystore Redis over the VPC Connector in europe-west1, so will see how we go.

**Comment by iamacarpet** [comment] 2019-11-20 11:06
I'm going to close this, as it kind of sits outside of the relms of this library.

As a quick update though, we do still see intermittent connectivity problems when talking to Redis over the Serverless VPC Connector.

Google have confirmed they've fixed a bunch of issues, but they are still investigating to see if there is anything else lurking.

I guess it's still in BETA at the moment and we'll hopefully see it all resolved for GA.

**Closed as completed by iamacarpet** 2019-11-20 11:06 UTC
